"""empty message

Revision ID: 392855e8905e
Revises: 8bb5d96168ad
Create Date: 2024-02-11 21:01:53.194606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392855e8905e'
down_revision = '8bb5d96168ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
