"""empty message

Revision ID: 40cbe4fad9d1
Revises: 98e897083f08
Create Date: 2024-02-22 03:00:17.163027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cbe4fad9d1'
down_revision = '98e897083f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_features',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('feature_type', sa.Enum('color', 'quality', 'others', name='ProductFeatureType'), nullable=True),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('is_price_effect', sa.Boolean(), nullable=False),
    sa.Column('price_effect_value', sa.Float(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('createdTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['production.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_features')
    # ### end Alembic commands ###
