"""empty message

Revision ID: 5334343f0174
Revises: d62f3d9a6795
Create Date: 2024-02-08 01:43:34.343473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5334343f0174'
down_revision = 'd62f3d9a6795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_tag',
    sa.Column('production_id', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['production.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('production_category',
    sa.Column('production_id', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production.id'], )
    )
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewOnly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('createdTime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updatedTime', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('production_image', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updatedTime')
        batch_op.drop_column('createdTime')
        batch_op.drop_column('enable')
        batch_op.drop_column('viewOnly')

    op.drop_table('production_category')
    op.drop_table('product_tag')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
