"""empty message

Revision ID: d62f3d9a6795
Revises: 7f81ea707218
Create Date: 2024-02-02 19:53:11.715165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62f3d9a6795'
down_revision = '7f81ea707218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('unit', sa.Enum('MetreMoraba', 'MetreMokaab', 'KiloGaram', 'Tona', name='product_unit'), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='StockStatus'), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('color', sa.Enum('NONE', 'BLUE', 'YELLOW', 'GRAY', name='Color'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('production_image',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('Image', 'Video', name='MediaType'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['production.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_image')
    op.drop_table('production')
    # ### end Alembic commands ###
